### ISSUE TITLE
MacOS port double-click of savefiles fails

### ISSUE THREAD

**Issue by NickMcConnell** [NickMcConnell/FAangband#276]
Error: “Too many (6) object flags!” 

My guess is it is trying to open with Angband, and it's to do with package ID (?terminology?) or some such.

**Comment by backwardsEric** [comment]
In main-cocoa.m, it's how mac_type is set in cocoa_file_open_hook() when the file type is FTYPE_SAVE.  There's a corresponding entry in the Info.plist file for the application that indicates the document types the application can handle.  Info.plist is generated from cocoa/FAangband-Cocoa.xml, and the document type corresponding to FTYPE_SAVE is the first dictionary in the CFBundleDocumentTypes key.  You want to set the string listed in CFBundleOSTypes key for that dictionary to be the same as the four character string you use for mac_type in cocoa_file_open_hook() when the file type is FTYPE_SAVE.

For testing, I changed 'SAVE' to 'FAA2' (I don't know if 'FAA2' is best; strings with all lowercase letters are reserved for Apple; the lists of known file type codes I found tend to be old and likely incomplete so I don't know if 'FAA2' is used for something else) in both places and rebuilt the application.  That was sufficient so that when I double-clicked on a newly generated save file, I got a prompt for what application to use rather than trying to open it in Angband.  For previously generated save files, one would have to either edit the file's metadata (matter can do that) but, unless there's a lot of files to change, right clicking on the file and selecting "Open with.." in the menu that appears is the easier way to get future double clicks on the file to work as expected.

The documentation for LaunchServices, https://developer.apple.com/library/archive/documentation/Carbon/Conceptual/LaunchServicesConcepts/LSCConcepts/LSCConcepts.html describes the criteria for which application is selected after double clicking on a file.  Giving the save file names an extension that would identify them as a FAangband-format save file rather than some other format would be another way to tell the Mac how to open the file.  That file extension would have to be mentioned in the Info.plist file (using the CFBundleTypeExtensions key for the dictionary describing save files).

**Comment by NickMcConnell** [comment]
Thanks, that was the sort of info I was looking for.

**Comment by backwardsEric** [comment]
That change got the part where the application advertises the file formats it supports.  It didn't affect how generated save files are labeled.  Both, as far as I know, are necessary.  To change how the save files are labeled, change 'SAVE' on line 5732 of main-cocoa.m to 'FAAN'.

**Comment by NickMcConnell** [comment]
Ah, thanks

**Comment by NickMcConnell** [comment]
Some days I just have trouble following simple instructions 😄
