### ISSUE TITLE
Bug: Repeat Last Action doesn't work as expected

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FAangband#349]
[n], the repeat last action command, seems to behave weirdly.

For instance, my command chain for casting Portal is m3a, but if I try hitting [n] immediately after casting it, nothing apparent happens. This has happened for a number of actions (but not all), and I haven't been able to figure out a common link or thought to note down other examples.

**Comment by backwardsEric** [comment]
What breaks repeating the casting of Portal (or any spell or action that moves the player) is that an auto pickup command is inserted after the move so that auto pickup command is what is repeated and not the command that triggered the move.  For the case of Portal (and other actions involving teleports), this behavior was newly introduced in https://github.com/angband/angband/pull/5329 so that the same bookkeeping is done after a teleport as after a regular move.
